#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=5
TOTAL_MINUTES=32

banner "Willagrams — Supabase setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Keep .env out of git" 1
say "This repo has no .env rule yet, so anything we save here would be committed."
if [[ -f .gitignore ]] && grep -qxF '.env' .gitignore; then
  note ".gitignore already ignores .env — nothing to do."
else
  printf '\n# Local service config (written by scripts/supabase-setup.sh)\n.env\n' >> .gitignore
  printf '  %s✓ added%s .env to .gitignore\n' "$GREEN" "$RESET"
fi
pause "Press Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the Supabase project" 8
say "You create the account and the project — this wizard never signs in for you."
open_url "https://supabase.com/dashboard/projects"
step "Sign in (GitHub is fine), then click 'New project'."
step "Name it 'willagrams'. Pick the region closest to your players."
step "Generate a database password and SAVE IT — it is shown once."
step "Wait for the project to finish provisioning (~2 min)."
say ""
step "Then go to Project Settings → Data API. Copy the Project URL."
ask SUPABASE_URL "Paste the Project URL (https://<ref>.supabase.co):"
step "Same page (or Settings → API Keys): copy the publishable / anon key."
note "This key is PUBLIC by design — it ships in the app and is fenced by RLS."
ask SUPABASE_ANON_KEY "Paste the publishable (anon) key:"
warn "Never copy the service_role / secret key into this app. It bypasses RLS."
ask_secret SUPABASE_DB_PASSWORD "Paste the database password you just saved:"
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
write_env SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"
pause "Press Enter to continue."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Sign in with Apple" 8
say "Native iOS sign-in needs only the bundle ID — no Services ID, no .p8 key."
note "That shortcut applies to native only. A web/OAuth fallback would need both."
warn "The Apple App ID capability needs a PAID Apple Developer membership (\$99/yr)."
say ""
if confirm "Do you have a paid Apple Developer membership?"; then
  open_url "https://developer.apple.com/account/resources/identifiers/list"
  step "Find (or register) the App ID for com.willagrams.Willagrams."
  step "In its Capabilities list, tick 'Sign in with Apple'. Save."
  pause "Press Enter once the capability is saved."
  open_url "https://supabase.com/dashboard/project/_/auth/providers"
  step "Open the 'Apple' provider and enable it."
  step "In the 'Client IDs' field, enter: com.willagrams.Willagrams"
  step "Leave Secret Key / Services ID empty — native flow does not use them."
  step "Save."
  write_env APPLE_BUNDLE_ID "com.willagrams.Willagrams"
  pause "Press Enter to continue."
else
  SKIPPED+=("Sign in with Apple — needs a paid Apple Developer membership, then re-run this wizard")
  warn "Skipping. Auth is blocked until you enrol; nothing else here depends on it."
  pause "Press Enter to continue."
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Supabase CLI — link the project" 9
if command -v supabase >/dev/null 2>&1; then
  note "CLI already installed: $(supabase --version 2>/dev/null | head -n1)"
else
  say "The CLI applies migrations and generates types. Installing via Homebrew."
  if confirm "Run 'brew install supabase/tap/supabase' now?"; then
    brew install supabase/tap/supabase || warn "brew install failed — install the CLI by hand"
  else
    SKIPPED+=("Supabase CLI install — brew install supabase/tap/supabase")
    warn "Skipped — later stages of this stage will not run."
  fi
fi
if command -v supabase >/dev/null 2>&1; then
  SUPABASE_PROJECT_REF="${SUPABASE_URL#https://}"
  SUPABASE_PROJECT_REF="${SUPABASE_PROJECT_REF%%.supabase.co*}"
  say ""
  say "Project ref read from your URL: ${SUPABASE_PROJECT_REF}"
  write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
  step "A browser tab will open for CLI login. Approve it, copy the token back."
  supabase login || warn "login failed — re-run 'supabase login' by hand"
  supabase link --project-ref "$SUPABASE_PROJECT_REF" \
    || warn "link failed — re-run 'supabase link --project-ref $SUPABASE_PROJECT_REF'"
  say ""
  note "supabase/config.toml already exists — 'supabase init' has been run for you."
  note "No migrations exist yet: /foundation writes supabase/migrations/**."
  note "Once it has, apply them with:  supabase db push"
fi
pause "Press Enter to continue."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Add the SDK to the Xcode project" 5
say "supabase-swift is the app's FIRST third-party package. Add it by hand in Xcode"
say "so the .xcodeproj records it — this wizard will not edit project.pbxproj."
note "Requires iOS 16+. This app targets iOS 17, so it is compatible."
open_url "https://github.com/supabase/supabase-swift"
step "In Xcode: File → Add Package Dependencies…"
step "URL: https://github.com/supabase/supabase-swift.git"
step "Dependency Rule: Up to Next Major Version, starting at 2.0.0"
step "Add these products to the Willagrams target: Auth, PostgREST, Realtime."
note "Skip Storage and Functions until something actually needs them."
pause "Press Enter once the package resolves and the app still builds."
say ""
say "The two values the online lane will consume from .env:"
note "  SUPABASE_URL       = ${SUPABASE_URL:-<unset>}"
note "  SUPABASE_ANON_KEY  = ${SUPABASE_ANON_KEY:+<captured, see .env>}${SUPABASE_ANON_KEY:-<unset>}"

finish
